[workspace]
members = [
    "packages/dojo_survivor",
    "packages/dojo_inventory_mgmt",
]
description = "Elysium Descent Dojo Game"
homepage = "https://github.com/okhaimie-dev/elysium_descent/"
cairo-version = "2.10.1"

[workspace.package]
version = "0.0.1"
edition = "2024_07"

[workspace.dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
cairo_test = "2.10.1"
starknet = "2.10.1"

[workspace.tool.fmt]
sort-module-level-items = true
