[package]
cairo-version = "=2.10.1"
name = "elysium_descent"
version = "0.0.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.1" }
starknet = "2.10.1"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.1" }
cairo_test = "2.10.1"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[profile.slot]
